### ISSUE TITLE
git@github.com:houssem-yahiaoui/fileupload-nodejs.git

### ISSUE THREAD

**Issue by ashutosh21414** [houssem-yahiaoui/fileupload-nodejs#2]
Hi, 
On hitting route POST /api/img, I am getting this error - 

TypeError: Cannot read property 'file' of undefined
    at router.post (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\routings\routing.js:50:29)
    at Layer.handle [as handle_request] (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\express\lib\router\index.js:275:10)
    at multipartBodyParser (C:\Users\aashh\Desktop\Work1\A\fileupload-nodejs\node_modules\busboy-body-parser\index.js:72:13)

I have tried resolving but found that the package is perfectly working on other system.
Debugging steps followed - 
1. Removed node_moules and reinstalled npm
2. Tried using bodyparser before busboy
3. Reset hard the repository with the origin

Any help is appreciated.

**Comment by houssem-yahiaoui** [comment]
@ashutosh21414 Please can you try over your POST /api/img  and comment everything there and add stdout the following : 
```javascript
console.log(req.files);
console.log(req.body)
```
The files will going to live inside the req.files object, also you probably the file object you're sending is not going with the name of "file" maybe it's another name, is so it will like this : **req.files.<object-name>,** because when you send your file over HTTP POST you will to give it a name so it be sent, that's why i recommend checking the **req.files** so you can grab the file object name.

Please try it and if it's not working, please do the stdout of the **req.files**  and pass to me the HTTP post request you're making or the screenshot e=if you're using postman.

Hope this helps.

**Comment by houssem-yahiaoui** [comment]
Closing this for now, in case you still having sme issue please reopen it.
